version: "3"
services:
  hmpps-education-and-work-plan-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-education-and-work-plan-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_AUTH_URL=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - DB_SERVER=education-and-work-plan-api-db:5432
      - DB_NAME=education-and-work-plan-api_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://education-and-work-plan-api-db:5432/education-and-work-plan-api_db
      - DB_USER=admin
      - DB_PASS=admin_password
      - DPR_USER=dpr_user
      - DPR_PASSWORD=dpr_password
      - HMPPS_SAR_ADDITIONALACCESSROLE=ROLE_EDUCATION_WORK_PLAN_VIEWER
      - PRISON_API_URL=https://prison-api-dev.prison.service.justice.gov.uk/
      - MANAGE_USERS_API_URL=https://manage-users-api-dev.hmpps.service.justice.gov.uk
      - CIAG_KPI_PROCESSING_RULE=PEF
      - PRISONER_SEARCH_API_URL=https://prisoner-search-dev.prison.service.justice.gov.uk
      - SERVICE_BASE_URL=http://localhost:8081"
      - PES_CONTRACT_START_DATE=2025-10-01

  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: education-and-work-plan-api-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=education-and-work-plan-api_db

networks:
  hmpps:
