%%
%% Mermaid Charts sequence diagram. View with the mermaid plugin for intellij or using the online Mermaid editor https://www.mermaidchart.com
%%

sequenceDiagram
  title : KPI 2

  actor Prisoner as Prisoner
  actor CIAG as CIAG
  participant PLP as PLP
  participant PLPDB as PLP DB
  participant DomainEvents as HMPPS Domain Events
  participant Integration as HMPPS Integration API
  participant Curious as Curious

  rect rgba(0, 200, 255, 0.4)
    Prisoner ->> DomainEvents: Prisoner enters prison
    note over Prisoner, DomainEvents: New or re-offending prisoner
    activate DomainEvents
    deactivate DomainEvents

    activate PLP
      note left of PLP: PLP API processes<br/>prisoner.received event<br/>reason: admission
      DomainEvents -) PLP: prison-offender-events.prisoner.received event
      alt Prisoner already has a PLP
        activate PLPDB
          PLP ->> PLPDB: Create or update Review Schedule record
          note right of PLPDB: Review deadline date<br/>set to today + 10 days
        deactivate PLPDB
        PLP -) DomainEvents: plp.review-schedule.updated event
      else Prisoner does not have a PLP<br/>eg. new prisoner, or re-offending prisoner from before PLP existed
        note over PLP: Refer to Induction process for KPI1 - CIAG KPI1 - PEF Apr 25 to Oct 25.mermaid
      end
    deactivate PLP
  end

  rect rgba(0, 200, 255, 0.4)
    Prisoner ->> DomainEvents: Prisoner transfers into prison
    note over Prisoner, DomainEvents: Existing prisoner transferring between prisons
    activate DomainEvents
    deactivate DomainEvents

    activate PLP
      note left of PLP: PLP API processes<br/>prisoner.received event<br/>reason: transferred
      DomainEvents -) PLP: prison-offender-events.prisoner.received event
      alt Prisoner already has a PLP
        activate PLPDB
          PLP ->> PLPDB: Create or update Review Schedule record
          note right of PLPDB: Review deadline date<br/>set to today + 10 days
        deactivate PLPDB
        PLP -) DomainEvents: plp.review-schedule.updated event
      else Prisoner does not have a PLP<br/>eg. new prisoner, or re-offending prisoner from before PLP existed
        note over PLP: Refer to Induction process for KPI1 - CIAG KPI1 - PEF Apr 25 to Oct 25.mermaid
      end
    deactivate PLP
  end

  rect rgba(0, 200, 255, 0.4)
    note over Prisoner, DomainEvents: Prisoner is released
    activate DomainEvents
    deactivate DomainEvents

    activate PLP
      note left of PLP: PLP API processes<br/>prisoner.released event
      DomainEvents -) PLP: prison-offender-events.prisoner.released event
      opt Prisoner has a Review scheduled
        PLP ->> PLPDB: Record exemption reason
        PLP -) DomainEvents: plp.review-schedule.updated event
      end
    deactivate PLP
  end

  rect rgba(0, 200, 255, 0.4)
    note over Prisoner, DomainEvents: Prisoner dies
    activate DomainEvents
    deactivate DomainEvents

    activate PLP
      note left of PLP: PLP API processes<br/>prisoner.released event<br/>nomisMovementReasonCode: DEC
      DomainEvents -) PLP: prison-offender-events.prisoner.released event
      opt Prisoner has a Review scheduled
        PLP ->> PLPDB: Record exemption reason
        PLP -) DomainEvents: plp.review-schedule.updated event
      end
    deactivate PLP
  end

  rect rgba(0, 200, 255, 0.4)
    activate CIAG
      activate PLP
        CIAG ->> PLP: Do prisoner's Review
        alt Prisoners Review could not be completed due to exemptions
          PLP ->> PLPDB: Record exemption reason
        else
          PLP ->> PLPDB: Record prisoner's review
        end
        PLP -) DomainEvents: plp.review-schedule.updated event
      deactivate PLP
    deactivate CIAG
  end

  rect rgba(0, 200, 255, 0.4)
    activate CIAG
      activate PLP
        CIAG ->> PLP: Clear prisoner's Review exemption
        PLP ->> PLPDB: Clear exemption reason
        PLP ->> PLPDB: Update Review Schedule record
        note right of PLPDB: Review deadline date<br/>set to today + 5 days (exclusions), or today + 10 days (exemptions)
        PLP -) DomainEvents: plp.review-schedule.updated event
      deactivate PLP
    deactivate CIAG
  end

  rect rgba(0, 255, 200, 0.4)
    activate Integration
      note left of Integration: HMPPS Integration API processes<br/>plp.review-schedule.updated event
      DomainEvents -) Integration: plp.review-schedule.updated event
      Integration -) DomainEvents: PLP_REVIEW_SCHEDULE_CHANGED event
    deactivate Integration
  end

  rect rgba(255, 100, 100, 0.4)
    activate Curious
      note left of Curious: Curious processes<br/>PLP_REVIEW_SCHEDULE_CHANGED event
      DomainEvents -) Curious: PLP_REVIEW_SCHEDULE_CHANGED event
      Curious ->> Integration: get prisoner's Review Schedule
      activate Integration
        Integration ->> PLP: get prisoner's Review Schedule
        activate PLP
          PLP ->> PLPDB: get prisoner's Review Schedule
          PLPDB ->> PLP: prisoner's Review Schedule
          PLP ->> Integration: prisoner's Review Schedule
        deactivate PLP
        Integration ->> Integration: Map prisoner's PLP Review Schedule into Integration API Review Schedule response
        Integration ->> Curious: prisoner's Review Schedule
      deactivate Integration
      note left of Curious: Curious processes prisoner's Review Schedule<br/>in order to produce reports
    deactivate Curious
  end

