version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@10
parameters:
  releases-slack-channel:
    type: string
    default: dps-releases
  java-version:
    type: string
    default: "25.0"
  postgres-version:
    type: string
    default: "15.5"
  localstack-version:
    type: string
    default: "3.6.0"
  java-options:
    type: string
    default: -Xmx2g -XX:MaxMetaspaceSize=1g -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1
jobs:
  validate:
    resource_class: "medium+"
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: << pipeline.parameters.java-version >>
      java_options: << pipeline.parameters.java-options >>
      postgres_tag: << pipeline.parameters.postgres-version >>
      postgres_db: "education_and_work_plan_api_db"
      postgres_username: "admin"
      postgres_password: "admin_password"
      localstack_tag: << pipeline.parameters.localstack-version >>
      services: "sqs,sns"
    environment:
      DB_SERVER: localhost
      DB_NAME: education_and_work_plan_api_db
      DB_USER: admin
      DB_PASS: admin_password
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew  --daemon check
      - run:
          command: ./gradlew --daemon combineJacocoReports
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: domain/goal/build/test-results
      - store_test_results:
          path: domain/timeline/build/test-results
      - run:
          name: Compress Build Reports Artifacts
          command: |
            tar -cvzf build-reports.tar \
            build/reports/tests \
            build/reports/jacoco \
            domain/learningandworkprogress/build/reports/tests \
            domain/learningandworkprogress/build/reports/jacoco \
            domain/personallearningplan/build/reports/tests \
            domain/personallearningplan/build/reports/jacoco \
            domain/timeline/build/reports/tests \
            domain/timeline/build/reports/jacoco
      - store_artifacts:
          path: build-reports.tar
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
