package uk.gov.justice.digital.hmpps.educationandworkplanapi.app.specialtests.resource.sar

import org.junit.jupiter.api.BeforeEach
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.reactive.server.WebTestClient
import uk.gov.justice.digital.hmpps.domain.randomValidPrisonNumber
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.IntegrationTestBase
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.client.prisonersearch.aValidPrisoner
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.config.MillisecondTickingClock
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.database.jpa.entity.induction.InductionScheduleCalculationRule
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.database.jpa.entity.induction.InductionScheduleStatus
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.ArchiveGoalRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.CompleteGoalRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.EmployabilitySkillRating
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.EmployabilitySkillSessionType
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.EmployabilitySkillType
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.PersonalInterestType
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.ReasonToArchiveGoal
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.ReviewScheduleStatus
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateActionPlanRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateEmployabilitySkillRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateGoalRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aFullyPopulatedCreateInductionRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidCreatePersonalSkillsAndInterestsRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidPersonalInterest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.review.aValidCreateActionPlanReviewRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.review.aValidUpdateReviewScheduleStatusRequest
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarIntegrationTestHelper
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarReportTest
import java.time.LocalDate
import java.util.UUID

// Run test with env var SAR_GENERATE_ACTUAL=true to generate actual SAR report content for the test data created in this test,
// which can be used to verify the format and content of the report generated by the Subject Access Request service.

@ActiveProfiles("integration-test", "ticking-clock")
class SarReportGenerationTest :
  IntegrationTestBase(),
  SarReportTest {
  private lateinit var prisonNumber: String

  @BeforeEach
  fun setup() {
    prisonNumber = randomValidPrisonNumber()
    // Reset the TickingClock current tick, which means the test and assertions will survive 999 calls to Instant.now() before the clock ticks over to the next second.
    // This is important because the SAR Report Generation test setup calls Instant.now() multiple times to setup the test data.
    // We need a controlled tick of the clock so that each entity saved is timestamped with an incremental time so that sorting
    // on timestamp works in a predicatable manner.
    // But we need to ensure the clock doesn't tick over to the next second as the generated report will then not match the expected report.
    // This is arguably slightly fragile in that the test setup is limited to 999 calls to Instant.now() before it ticks
    // over to the next second (because the precision of the timestamp fields in flyway is `timestamp(3)`), but it should
    // be OK.
    if (clock is MillisecondTickingClock) {
      (clock as MillisecondTickingClock).resetMilliSecondsTick()
    }
  }

  override fun getWebTestClientInstance(): WebTestClient = webTestClient

  override fun getSarHelper(): SarIntegrationTestHelper = sarIntegrationTestHelper

  override fun getPrn(): String = prisonNumber

  override fun setupTestData() {
    with(aValidPrisoner(prisonerNumber = prisonNumber, prisonId = "MDI")) {
      createPrisonerAPIStub(prisonNumber, this)
    }
    val inductionScheduleReference = UUID.randomUUID()
    val inductionDeadlineDate = LocalDate.parse("2026-06-20")
    createInductionSchedule(
      prisonNumber,
      reference = inductionScheduleReference,
      deadlineDate = inductionDeadlineDate,
      status = InductionScheduleStatus.SCHEDULED,
      inductionScheduleCalculationRule = InductionScheduleCalculationRule.NEW_PRISON_ADMISSION,
    )
    createInductionScheduleHistory(
      prisonNumber,
      reference = inductionScheduleReference,
      deadlineDate = inductionDeadlineDate,
      status = InductionScheduleStatus.SCHEDULED,
      version = 1,
    )
    createInductionScheduleHistory(
      prisonNumber,
      reference = inductionScheduleReference,
      deadlineDate = inductionDeadlineDate,
      status = InductionScheduleStatus.EXEMPT_TEMP_ABSENCE,
      version = 2,
    )
    createInductionScheduleHistory(
      prisonNumber,
      reference = inductionScheduleReference,
      deadlineDate = inductionDeadlineDate,
      status = InductionScheduleStatus.SCHEDULED,
      version = 3,
    )
    createInduction(
      prisonNumber,
      createInductionRequest = aFullyPopulatedCreateInductionRequest(
        personalSkillsAndInterests = aValidCreatePersonalSkillsAndInterestsRequest(
          skills = null,
          interests = listOf(
            aValidPersonalInterest(interestType = PersonalInterestType.COMMUNITY, interestTypeOther = null),
            aValidPersonalInterest(interestType = PersonalInterestType.OTHER, interestTypeOther = "Varied interests"),
          ),
        ),
        employabilitySkills = listOf(
          aValidCreateEmployabilitySkillRequest(
            prisonId = "BXI",
            employabilitySkillType = EmployabilitySkillType.COMMUNICATION,
            employabilitySkillRating = EmployabilitySkillRating.QUITE_CONFIDENT,
            evidence = "Spoke confidently during the CIAG Induction",
            sessionType = EmployabilitySkillSessionType.CIAG_INDUCTION,
            sessionTypeDescription = null,
          ),
          aValidCreateEmployabilitySkillRequest(
            prisonId = "MDI",
            employabilitySkillType = EmployabilitySkillType.COMMUNICATION,
            employabilitySkillRating = EmployabilitySkillRating.VERY_CONFIDENT,
            evidence = "Spoke confidently and with clarity during the Metal Working Workshop",
            sessionType = EmployabilitySkillSessionType.INDUSTRIES_REVIEW,
            sessionTypeDescription = "Metal Working Workshop",
          ),
          aValidCreateEmployabilitySkillRequest(
            prisonId = "MDI",
            employabilitySkillType = EmployabilitySkillType.ADAPTABILITY,
            employabilitySkillRating = EmployabilitySkillRating.NOT_CONFIDENT,
            evidence = "Struggled to adapt to the new working environment during the Metal Working Industry Workshop",
            sessionType = EmployabilitySkillSessionType.INDUSTRIES_REVIEW,
            sessionTypeDescription = "Metal Working Workshop",
          ),
        ),
        conductedAt = LocalDate.parse("2025-06-01"),
        conductedBy = "John Smith",
        conductedByRole = "Peer mentor",
      ),
    )
    createActionPlan(
      prisonNumber,
      createActionPlanRequest = aValidCreateActionPlanRequest(
        goals = listOf(
          aValidCreateGoalRequest(
            title = "Goal 1",
            targetCompletionDate = LocalDate.parse("2050-12-31"), // Target completion date MUST be in the future so set a very long date to prevent fragile test failure
          ),
          aValidCreateGoalRequest(
            title = "Goal 2",
            targetCompletionDate = LocalDate.parse("2050-12-31"),
          ),
          aValidCreateGoalRequest(
            title = "Goal 3",
            targetCompletionDate = LocalDate.parse("2050-12-31"),
          ),
        ),
      ),
    )

    val goals = getActionPlan(prisonNumber).goals
    completeGoal(
      prisonNumber,
      CompleteGoalRequest(
        goalReference = goals.find { it.title == "Goal 2" }!!.goalReference,
        prisonId = "MDI",
        note = "Goal completed on time",
      ),
    )
    archiveGoal(
      prisonNumber,
      ArchiveGoalRequest(
        goalReference = goals.find { it.title == "Goal 3" }!!.goalReference,
        prisonId = "MDI",
        reason = ReasonToArchiveGoal.OTHER,
        reasonOther = "Staff can no longer support him to achieve this goal",
        note = "Goal archived as no longer appropriate",
      ),
    )

    // The next review date will have been calculated based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next (first) review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2025-08-01"),
      latestReviewDate = LocalDate.parse("2025-08-10"),
    )

    // perform a couple of reviews
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Review went well",
        conductedAt = LocalDate.parse("2025-08-05"),
        conductedBy = "Barnie Jones",
        conductedByRole = "Peer mentor",
      ),
    )
    // The last review will have calculated the next review date based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2026-01-25"),
      latestReviewDate = LocalDate.parse("2026-02-05"),
    )
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Second review went really well",
        conductedAt = LocalDate.parse("2026-01-29"),
        conductedBy = null,
        conductedByRole = null,
      ),
    )
    // The last review will have calculated the next review date based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2026-03-01"),
      latestReviewDate = LocalDate.parse("2026-03-10"),
    )
    updateReviewStatus(
      prisonNumber,
      updateReviewScheduleStatusRequest = aValidUpdateReviewScheduleStatusRequest(
        status = ReviewScheduleStatus.EXEMPT_PRISONER_DRUG_OR_ALCOHOL_DEPENDENCY,
        exemptionReason = "Prisoner is currently in a drug and alcohol rehabilitation programme and not able to participate in a review at this time",
      ),
    )
  }
}
