package uk.gov.justice.digital.hmpps.educationandworkplanapi.app.specialtests.resource.sar

import org.junit.jupiter.api.BeforeEach
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.reactive.server.WebTestClient
import uk.gov.justice.digital.hmpps.domain.randomValidPrisonNumber
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.IntegrationTestBase
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.client.prisonersearch.aValidPrisoner
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.PersonalInterestType
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateActionPlanRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateEmployabilitySkillRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateGoalRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aFullyPopulatedCreateInductionRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidCreatePersonalSkillsAndInterestsRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidPersonalInterest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.review.aValidCreateActionPlanReviewRequest
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarIntegrationTestHelper
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarReportTest
import java.time.LocalDate

// Run test with env var SAR_GENERATE_ACTUAL=true to generate actual SAR report content for the test data created in this test,
// which can be used to verify the format and content of the report generated by the Subject Access Request service.

@ActiveProfiles("integration-test", "fixed-clock")
class SarReportGenerationTest :
  IntegrationTestBase(),
  SarReportTest {
  private lateinit var prisonNumber: String

  @BeforeEach
  fun setup() {
    prisonNumber = randomValidPrisonNumber()
  }

  override fun getWebTestClientInstance(): WebTestClient = webTestClient

  override fun getSarHelper(): SarIntegrationTestHelper = sarIntegrationTestHelper

  override fun getPrn(): String = prisonNumber

  override fun setupTestData() {
    with(aValidPrisoner(prisonerNumber = prisonNumber, prisonId = "MDI")) {
      createPrisonerAPIStub(prisonNumber, this)
    }
    createInductionSchedule(prisonNumber)
    createInduction(
      prisonNumber,
      createInductionRequest = aFullyPopulatedCreateInductionRequest(
        personalSkillsAndInterests = aValidCreatePersonalSkillsAndInterestsRequest(
          skills = null,
          interests = listOf(
            aValidPersonalInterest(interestType = PersonalInterestType.COMMUNITY),
            aValidPersonalInterest(interestType = PersonalInterestType.OTHER, interestTypeOther = "Varied interests"),
          ),
        ),
        employabilitySkills = listOf(aValidCreateEmployabilitySkillRequest()),
        conductedAt = LocalDate.parse("2025-06-01"),
        conductedBy = "John Smith",
        conductedByRole = "Peer mentor",
      ),
    )
    createActionPlan(
      prisonNumber,
      createActionPlanRequest = aValidCreateActionPlanRequest(
        goals = listOf(
          aValidCreateGoalRequest(
            title = "Goal 1",
            targetCompletionDate = LocalDate.parse("2050-12-31"), // Target completion date MUST be in the future so set a very long date to prevent fragile test failure
          ),
        ),
      ),
    )
    // The next review date will have been calculated based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next (first) review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2025-08-01"),
      latestReviewDate = LocalDate.parse("2025-08-10"),
    )

    // perform a couple of reviews
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Review went well",
        conductedAt = LocalDate.parse("2025-08-05"),
        conductedBy = "Barnie Jones",
        conductedByRole = "Peer mentor",
      ),
    )
    // The last review will have calculated the next review date based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2026-01-25"),
      latestReviewDate = LocalDate.parse("2026-02-05"),
    )
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Second review went really well",
        conductedAt = LocalDate.parse("2026-01-29"),
        conductedBy = null,
        conductedByRole = null,
      ),
    )
    // The last review will have calculated the next review date based on "today"; therefore it changes every day and the expected HTML output will not match
    // manually set the next review date to a fixed date to prevent fragile test failure
    updateReviewScheduleReviewDates(
      prisonNumber,
      earliestReviewDate = LocalDate.parse("2026-03-01"),
      latestReviewDate = LocalDate.parse("2026-03-10"),
    )
  }
}
