server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: 'jdbc:h2:mem:education_and_work_plan_api_db;MODE=PostgreSQL'
    username: admin
    password: admin_password

  h2:
    console:
      enabled: true

  # Include h2 specific migration scripts
  flyway:
    locations: classpath:/db/migration,classpath:/db/h2

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

hmpps.sqs:
  provider: localstack
  queues:
    educationandworkplan:
      queueName: education-and-work-plan-queue
      subscribeFilter: "{\"eventType\":[\"ciag-induction.created\", \"ciag-induction.updated\"]}"
      dlqName: education-and-work-plan-dead-letter-queue
      subscribeTopicId: domainevents
      dlqMaxReceiveCount: 1
      visibilityTimeout: 1
    domaineventsqueue:
      queueName: domainevents-queue
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic

prison-api:
  client:
    id: prison-api-client-id
    secret: client-secret

apis:
  prison-api:
    url: http://localhost:9093

featureToggles:
  call-prison-api-enabled: true
