server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: 'jdbc:h2:mem:education_and_work_plan_api_db;MODE=PostgreSQL'
    username: admin
    password: admin_password

  h2:
    console:
      enabled: true

  # Include h2 specific migration scripts
  flyway:
    locations: classpath:/db/migration/common,classpath:/db/h2

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

prison-api:
  client:
    id: prison-api-client-id
    secret: client-secret

apis:
  prison-api:
    url: http://localhost:9093
