# Export database to Analytical Platform data pipeline
#
# Sets up a CronJob pod that uses the `ministryofjustice/data-engineering-data-extractor` docker image to extract
# all tables to CSV and upload to the Analytical Platform S3 bucket.
#
apiVersion: batch/v1
kind: CronJob
metadata:
  name: export-database-to-analytical-platform-cronjob
spec:
  suspend: true
  schedule: "0 1 * * *" # 1am every day
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: data-extractor-analytics
              image: ministryofjustice/data-engineering-data-extractor:v1
              imagePullPolicy: Always
              args: ["extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh"]
              env:
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: rds-postgresql-instance-output
                      key: rds_instance_address
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: rds-postgresql-instance-output
                      key: database_name
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: rds-postgresql-instance-output
                      key: database_username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rds-postgresql-instance-output
                      key: database_password
                - name: S3_DESTINATION
                  valueFrom:
                    secretKeyRef:
                      name: analytical-platform-reporting-s3-bucket
                      key: destination_bucket
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: analytical-platform-reporting-s3-bucket
                      key: access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: analytical-platform-reporting-s3-bucket
                      key: secret_access_key
                - name: AWS_DEFAULT_REGION
                  value: eu-west-2
                - name: SAVE_EVENTS_LOG
                  value: "true"
