package uk.gov.justice.digital.hmpps.educationandworkplanapi.app.resource.sar

import org.junit.jupiter.api.BeforeEach
import org.springframework.test.web.reactive.server.WebTestClient
import uk.gov.justice.digital.hmpps.domain.randomValidPrisonNumber
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.IntegrationTestBase
import uk.gov.justice.digital.hmpps.educationandworkplanapi.app.database.jpa.entity.review.ReviewScheduleStatus
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.PersonalInterestType
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateActionPlanRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateEmployabilitySkillRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.actionplan.aValidCreateGoalRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aFullyPopulatedCreateInductionRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidCreatePersonalSkillsAndInterestsRequest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.induction.aValidPersonalInterest
import uk.gov.justice.digital.hmpps.educationandworkplanapi.resource.model.review.aValidCreateActionPlanReviewRequest
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarIntegrationTestHelper
import uk.gov.justice.digital.hmpps.subjectaccessrequest.SarReportTest
import java.time.LocalDate

// Run test with env var SAR_GENERATE_ACTUAL=true to generate actual SAR report content for the test data created in this test,
// which can be used to verify the format and content of the report generated by the Subject Access Request service.

class SarReportGenerationTest :
  IntegrationTestBase(),
  SarReportTest {
  private lateinit var prisonNumber: String

  @BeforeEach
  fun setup() {
    prisonNumber = randomValidPrisonNumber()
  }

  override fun getWebTestClientInstance(): WebTestClient = webTestClient

  override fun getSarHelper(): SarIntegrationTestHelper = sarIntegrationTestHelper

  override fun getPrn(): String = prisonNumber

  override fun setupTestData() {
    createInduction(
      prisonNumber,
      createInductionRequest = aFullyPopulatedCreateInductionRequest(
        personalSkillsAndInterests = aValidCreatePersonalSkillsAndInterestsRequest(
          skills = null,
          interests = listOf(
            aValidPersonalInterest(interestType = PersonalInterestType.COMMUNITY),
            aValidPersonalInterest(interestType = PersonalInterestType.OTHER, interestTypeOther = "Varied interests"),
          ),
        ),
        employabilitySkills = listOf(aValidCreateEmployabilitySkillRequest()),
      ),
    )
    createActionPlan(
      prisonNumber,
      createActionPlanRequest = aValidCreateActionPlanRequest(
        goals = listOf(aValidCreateGoalRequest(title = "Goal 1")),
      ),
    )
    createReviewScheduleRecord(
      prisonNumber,
      status = ReviewScheduleStatus.SCHEDULED,
      earliestDate = LocalDate.parse("2025-12-25"),
      latestDate = LocalDate.parse("2026-01-05"),
    )
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Review went well",
        conductedAt = LocalDate.parse("2026-01-01"),
        conductedBy = "Barnie Jones",
        conductedByRole = "Peer mentor",
      ),
    )
    createActionPlanReview(
      prisonNumber,
      createActionPlanReviewRequest = aValidCreateActionPlanReviewRequest(
        note = "Second review went really well",
        conductedAt = LocalDate.parse("2026-03-29"),
        conductedBy = null,
        conductedByRole = null,
      ),
    )
  }
}
