---
# Per environment values which override defaults in hmpps-education-and-work-plan-api/values.yaml

generic-service:
  # TODO - RR-502 - set this back to 2
  replicaCount: 1

  ingress:
    host: learningandworkprogress-api-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '00 21 * * 1-5' # Stop at 9.00pm UTC Monday-Friday

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    # TODO - RR-502 - Remove `CIAG_INDUCTION_API_URL` and `CIAG_INDUCTION_DATA_MIGRATION_ENABLED`
    CIAG_INDUCTION_API_URL: "https://ciag-induction-api-dev.hmpps.service.justice.gov.uk"
    CIAG_INDUCTION_DATA_MIGRATION_ENABLED: "true"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
