---
# Per environment values which override defaults in hmpps-education-and-work-plan-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: learningandworkprogress-api-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '00 21 * * 1-5' # Stop at 9.00pm UTC Monday-Friday

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    CALL_PRISON_API_ENABLED: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

generic-data-analytics-extractor:
  serviceAccountName: hmpps-education-and-work-plan-dev-to-ap-s3
