name: Deploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - dev
          - preprod
          - prod
        default: 'dev'
      version:
        description: version to be deployed to the environment - must already exist.
        required: true
        default: ''
        type: string

permissions:
  contents: read

jobs:
  helm_lint:
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@d79e83be2cc392b981dd92c8f6f85007d18032e9 # v2 WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  deploy_env:
    name: Deploy to environment
    needs:
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@d79e83be2cc392b981dd92c8f6f85007d18032e9 # v2 WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.version }}
      slack_notification: 'false' # if 'true', it needs a valid (NON)PROD_RELEASES_SLACK_CHANNEL variable to be set
